articles/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    path('<int:pk>/edit/', views.ArticleUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', views.ArticleDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='delete'),
    path('new/', views.ArticleCreateView.as_view(), name='create'),
    path('', views.ArticleListView.as_view(), name='index'),
]

newspaper_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('articles/', include('articles.urls')),
    path('', include('pages.urls'))
]

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup')
]

articles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.


class Article(models.Model):
    title = models.CharField('Título', max_length=255)
    body = models.TextField('Corpo')
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), verbose_name='Autor', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:detail', args=(str(self.id),))

    class Meta:
        verbose_name = 'Artigo'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE,
                                verbose_name='Artigo', related_name='comments')
    comment = models.CharField('Comentário', max_length=140)
    author = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('article:detail', args=(str(self.article.pk),))

    class Meta:
        verbose_name = 'Comentário'

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField('Idade', null=True, blank=True)

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'age',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'age',)

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Article

# Create your views here.


class ArticleViewMixin(LoginRequiredMixin):
    model = Article
    login_url = 'login'


class ArticleListView(ArticleViewMixin, ListView):
    template_name = 'articles/index.html'


class ArticleDetailView(ArticleViewMixin, DetailView):
    template_name = 'articles/detail.html'


class ArticleCreateView(ArticleViewMixin, CreateView):
    fields = ('title', 'body',)
    template_name = 'articles/create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(ArticleViewMixin, UserPassesTestMixin, UpdateView):
    fields = ('title', 'body', )
    template_name = 'articles/update.html'

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(ArticleViewMixin, UserPassesTestMixin, DeleteView):
    template_name = 'articles/delete.html'
    success_url = reverse_lazy('article:index')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

pages/views.py
from django.views.generic.base import TemplateView

# Create your views here.


class HomePageView(TemplateView):
    template_name = 'pages/home.html'

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm

# Create your views here.


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Criar artigo{% endblock title %}

{% block content %}
    <h2>Novo Artigo</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success ml-2">Salvar</button>
        <a href="{% url 'article:index' %}">cancelar</a>
    </form>
{% endblock content %}

articles/templates/articles/delete.html
{% extends 'base.html' %}

{% block title %}Excluir {{ object.title }}?{% endblock title %}

{% block content %}
    <h2>Excluir</h2>
    <form method="post">
        {% csrf_token %}
        <p>Você tem certeza de que quer apagar o artigo "{{ object.title }}"</p>
        <button class="btn btn-danger ml-2" type="submit">Confirmar</button>
        <a href="{% url 'article:detail' object.pk %}">cancelar</a>
    </form>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }} - Newspaper.com{% endblock title %}

{% block content %}
    <div class="article-entry">
        <h2>{{ object.title }}</h2>
        <p>por {{ object.author }} | {{ object.date }}</p>
        <p>{{ object.body }}</p>
    </div>
    <p>
        <a href="{% url 'article:update' object.pk %}">Editar</a> |
        <a href="{% url 'article:delete' object.pk %}">Apagar</a>
    </p>
    <p>Voltar para <a href="{% url 'article:index' %}">o início</a></p>
    <div class="jumbotron">
        {% for comment in object.comments.all %}
            <p>
                <span>{{ comment.author }}</span>
                {{ comment }}
            </p>
        {% endfor %}
    </div>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Artigos{% endblock title %}

{% block content %}
    {% for article in object_list %}
        <div class="card">
            <a href="{% url 'article:detail' article.pk %}">
                <div class="card-header">
                    <span class="font-weight-bold">{{ article.title }}</span> &middot;
                    <span class="text-muted">por {{ article.author }} | {{ article.date }}</span>
                </div>
            </a>
            <div class="card-body">
                <p>{{ article.body }}</p>
                <a href="{% url 'article:update' article.pk %}">Editar</a> |
                <a href="{% url 'article:delete' article.pk %}">Apagar</a>
            </div>
            <div class="card-footer">
                {% for comment in article.comments.all %}
                    <p>
                        <span class="font-weight-bold">{{ comment.author }} &middot;</span>
                        {{ comment }}
                    </p>
                {% endfor %}
            </div>
        </div>
        <br/>
    {% endfor %}
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Atualizar {{ object.title }}{% endblock title %}

{% block content %}
    <h2>Editar</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info ml-2" type="submit">Atualizar</button>
        <a href="{% url 'article:detail' object.pk %}">cancelar</a>
    </form>
{% endblock content %}

pages/templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Newspaper app</h1>
        <p class="lead">A Newspaper website built with Django.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'article:index' %}" role="button">Ver artigos</a>
        </p>
    </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">

        <title>{% block title %}Newspaper App{% endblock title %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
            <a class="navbar-brand" href="{% url 'pages:home' %}">Newspaper</a>
            {% if user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a href="{% url 'article:create' %}">+ New</a></li>
                </ul>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
                        <a href="{% url 'users:signup' %}" class="btn btn-primary ml-2">Sign up</a>
                    </form>
                {% endif %}
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    </body>
</html>

users/templates/users/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success" type="submit">Sign Up</button>
    </form>
{% endblock content %}